# Generated by Django 4.2.3 on 2023-07-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_remove_song_playlists_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
